version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: filemanager_postgres
    restart: always
    environment:
      POSTGRES_DB: filedb
      POSTGRES_USER: fileuser
      POSTGRES_PASSWORD: filepass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: filemanager_minio
    restart: always
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - minio_data:/data

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.2
    container_name: filemanager_keycloak
    command: start-dev
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: filedb
      KC_DB_USERNAME: fileuser
      KC_DB_PASSWORD: filepass
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  file-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filemanager_app
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - minio
      - keycloak
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/filedb
      SPRING_DATASOURCE_USERNAME: fileuser
      SPRING_DATASOURCE_PASSWORD: filepass
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      KEYCLOAK_SERVER_URL: http://keycloak:8080
      KEYCLOAK_REALM: file-service
      KEYCLOAK_CLIENT_ID: file-manager

volumes:
  pgdata:
  minio_data:
